# Generated by Django 4.2.1 on 2023-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valhalla', '0003_promotion_prestige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestige',
            name='Prestige_Level',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='prestige',
            name='last_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestige',
            name='purchase_total',
            field=models.PositiveIntegerField(default=0, max_length=200),
        ),
    ]
