# Generated by Django 4.2.1 on 2023-06-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valhalla', '0004_alter_prestige_prestige_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valhalla.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valhalla.product')),
            ],
        ),
    ]
